// This package provides a simple way to ensure that only one instance of an application is running at a time. It uses file locking to achieve this, and it provides a nice error message if another instance is already running. The lock file is stored in the system's temporary directory, and it contains the PID of the running instance. If another instance tries to acquire the lock, it will read the PID from the lock file and check if the process is still running, providing helpful information to the user about how to stop the running instance or remove a stale lock file.
package singleton

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"

	"github.com/gofrs/flock"
)

type InstanceLock struct {
	fileLock *flock.Flock
	lockFile string
}

// / returns an InstanceLock for the given lock file path. The caller is responsible for calling LockOrExit or Lock to acquire the lock, and Unlock to release it.
// the lock file is custom in this constructor, so the caller can specify a custom path or use the default one generated by getLockFilePath. This allows for more flexibility in how the lock is used and where the lock file is stored.
func NewInstanceLock(lockFilePath string) *InstanceLock {
	return &InstanceLock{
		fileLock: flock.New(lockFilePath),
		lockFile: lockFilePath,
	}
}

func NewProcessLock() *InstanceLock {

	/// app name is always the name of the executable, so we can use it to generate a unique lock file path. This ensures that different applications will not interfere with each other's locks, and it also provides a clear and consistent naming convention for the lock files.
	binName := filepath.Base(os.Args[0])

	lockFile := getLockFilePath(binName)
	return NewInstanceLock(lockFile)
}

// LockOrExit tries to acquire the lock. If it fails, it reads the PID from
// the lock file, prints a pretty error message, and exits with code 1.
func (il *InstanceLock) LockOrExit() {
	locked, err := il.fileLock.TryLock()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error trying to acquire lock: %v\n", err)
		os.Exit(1)
	}

	if !locked {
		// Lock is held by another instance, read the PID and print it
		pid := il.readPIDFromLockFile()
		il.printAlreadyRunningMessage(pid)
		os.Exit(1)
	}

	// Successfully acquired the lock, now write our PID
	if err := il.writePIDToLockFile(); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing PID to lock file: %v\n", err)
		il.fileLock.Unlock()
		os.Exit(1)
	}
}

// Lock tries to acquire the lock and write the PID. Returns error if fails.
func (il *InstanceLock) Lock() error {
	locked, err := il.fileLock.TryLock()
	if err != nil {
		return err
	}
	if !locked {
		return os.ErrExist
	}

	// Write our PID to the lock file
	if err := il.writePIDToLockFile(); err != nil {
		il.fileLock.Unlock()
		return err
	}

	return nil
}

// Unlock releases the lock
func (il *InstanceLock) Unlock() error {
	return il.fileLock.Unlock()
}

// writePIDToLockFile writes the current process ID to the lock file
func (il *InstanceLock) writePIDToLockFile() error {
	f, err := os.OpenFile(il.lockFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return err
	}
	defer f.Close()

	_, err = f.WriteString(strconv.Itoa(os.Getpid()))
	return err
}

// readPIDFromLockFile reads the PID from the lock file
func (il *InstanceLock) readPIDFromLockFile() int {
	data, err := os.ReadFile(il.lockFile)
	if err != nil {
		return -1
	}

	pid, err := strconv.Atoi(strings.TrimSpace(string(data)))
	if err != nil {
		return -1
	}

	return pid
}

// printAlreadyRunningMessage prints a pretty error message when another instance is running
func (il *InstanceLock) printAlreadyRunningMessage(pid int) {
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "╔════════════════════════════════════════════════════════════╗")
	fmt.Fprintln(os.Stderr, "║                                                            ║")
	fmt.Fprintln(os.Stderr, "║          Another instance is already running!              ║")
	fmt.Fprintln(os.Stderr, "║                                                            ║")
	fmt.Fprintln(os.Stderr, "╚════════════════════════════════════════════════════════════╝")
	fmt.Fprintln(os.Stderr, "")

	if pid > 0 {
		processRunning := isProcessRunning(pid)
		if processRunning {
			fmt.Fprintf(os.Stderr, "  Process ID: %d (running)\n", pid)
			fmt.Fprintf(os.Stderr, "  Lock file: %s\n", il.lockFile)
			fmt.Fprintln(os.Stderr, "")
			fmt.Fprintf(os.Stderr, "  To stop the running instance, use: kill %d\n", pid)
		} else {
			fmt.Fprintf(os.Stderr, "  Process ID: %d (stale - process not running)\n", pid)
			fmt.Fprintf(os.Stderr, "  Lock file: %s\n", il.lockFile)
			fmt.Fprintln(os.Stderr, "")
			fmt.Fprintf(os.Stderr, "  The lock file may be stale. Remove it with: rm %s\n", il.lockFile)
		}
	} else {
		fmt.Fprintf(os.Stderr, "  Lock file: %s\n", il.lockFile)
		fmt.Fprintln(os.Stderr, " Could not read PID from lock file")
	}

	fmt.Fprintln(os.Stderr, "")
}

// getLockFilePath returns the path to the lock file for the given application name
func getLockFilePath(appName string) string {
	if appName == "" {
		appName = filepath.Base(os.Args[0])
	}

	lockPath := filepath.Join(os.TempDir(), "go-lock")
	_ = os.MkdirAll(lockPath, 0755)

	return filepath.Join(lockPath, appName+".lock")
}

// isProcessRunning checks if a process with the given PID is running
func isProcessRunning(pid int) bool {
	process, err := os.FindProcess(pid)
	if err != nil {
		return false
	}
	// Send signal 0 to check if process exists without actually sending a signal
	err = process.Signal(os.Signal(syscall.Signal(0)))
	return err == nil
}
